[package]
name = "ed25519-dalek"
version = "0.6.2"
authors = ["Isis Lovecruft <isis@patternsinthevoid.net>"]
readme = "README.md"
license = "BSD-3-Clause"
repository = "https://github.com/dalek-cryptography/ed25519-dalek"
homepage = "https://dalek.rs"
documentation = "https://docs.rs/ed25519-dalek"
keywords = ["cryptography", "ed25519", "curve25519", "signature", "ECC"]
categories = ["cryptography", "no-std"]
description = "Fast and efficient ed25519 EdDSA key generations, signing, and verification in pure Rust."
exclude = [ ".gitignore", "TESTVECTORS", "res/*" ]

[badges]
travis-ci = { repository = "dalek-cryptography/ed25519-dalek", branch = "master"}

[dependencies.curve25519-dalek]
version = "0.17"
default-features = false

[dependencies.subtle]
version = "0.6"
default-features = false

[dependencies.rand]
version = "0.5.0-pre.2"
default-features = false

[dependencies.digest]
version = "^0.7"

[dependencies.generic-array]
# same version that digest depends on
version = "0.9"

[dependencies.serde]
version = "^1.0"
optional = true

[dependencies.sha2]
version = "^0.7"
optional = true

[dependencies.failure]
version = "^0.1.1"
default-features = false

[dev-dependencies]
hex = "^0.3"
sha2 = "^0.7"
bincode = "^0.9"

[features]
default = ["std", "u64_backend"]
# We don't add "rand/std" here because it would enable a bunch of Fuchsia dependencies.
std = ["subtle/std", "curve25519-dalek/std"]
bench = []
nightly = ["curve25519-dalek/nightly", "subtle/nightly", "rand/nightly"]
asm = ["sha2/asm"]
yolocrypto = ["curve25519-dalek/yolocrypto"]
u64_backend = ["curve25519-dalek/u64_backend"]
u32_backend = ["curve25519-dalek/u32_backend"]
avx2_backend = ["curve25519-dalek/avx2_backend"]
