[package]
name = "ed25519-dalek"
version = "0.5.0"
authors = ["Isis Lovecruft <isis@torproject.org>"]
readme = "README.md"
license = "BSD-3-Clause"
repository = "https://github.com/isislovecruft/ed25519-dalek"
homepage = "https://code.ciph.re/isis/ed25519-dalek"
documentation = "https://docs.rs/ed25519-dalek"
keywords = ["cryptography", "ed25519", "curve25519", "signature", "ECC"]
categories = ["cryptography", "no-std"]
description = "Fast and efficient ed25519 EdDSA key generations, signing, and verification in pure Rust."
exclude = [ ".gitignore", "TESTVECTORS", "res/*" ]

[badges]
travis-ci = { repository = "isislovecruft/ed25519-dalek", branch = "master"}

[dependencies]
arrayref = "0.3.4"

[dependencies.curve25519-dalek]
version = "^0.12"
default-features = false

[dependencies.subtle]
version = "^0.3"
default-features = false

[dependencies.rand]
optional = true
version = "^0.3"

[dependencies.digest]
version = "^0.6"

[dependencies.generic-array]
# same version that digest depends on
version = "^0.8"

[dependencies.serde]
version = "^1.0"
optional = true

[dependencies.sha2]
version = "^0.6"
optional = true

[dev-dependencies]
hex = "0.2"
sha2 = "^0.6"
bincode = "^0.9"

[features]
default = ["std"]
std = ["rand", "curve25519-dalek/std"]
bench = []
nightly = ["curve25519-dalek/nightly"]
asm = ["sha2/asm"]

